### ISSUE TITLE
HIGtools crash.

### ISSUE THREAD

**Issue by JustABiscuit** [PoopenfartenDevelopment/HIGTools#8]
[crash-2022-11-17_20.08.41-client.txt](https://github.com/RedCarlos26/HIGTools/files/10041976/crash-2022-11-17_20.08.41-client.txt)

in the crash report you can see the crash. I can not make up any of that shit so. pls fix

**Comment by RacoonDog** [comment]
yes you can

**Comment by RedCarlos26** [comment]
Try reproducing the crash without other meteor addons please

**Comment by RedCarlos26** [comment]
@JustABiscuit

**Comment by JustABiscuit** [comment]
No?

**Comment by JustABiscuit** [comment]
It is fixed now.

**Comment by RedCarlos26** [comment]
Great
